"""change roles model and tasks model. Rename tgaccounts model

Revision ID: d6076d46d8a8
Revises: 184df881dc21
Create Date: 2023-08-01 18:55:45.320560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd6076d46d8a8'
down_revision = '184df881dc21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'payment_action')
    op.drop_column('roles', 'bot_action')
    op.drop_column('roles', 'role_action')
    op.drop_column('roles', 'staff_action')
    op.add_column('tasks', sa.Column('settings', sa.JSON(), server_default='{}', nullable=False))
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
               nullable=False)
    op.alter_column('tasks', 'job_start',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
               nullable=False)
    op.rename_table('tgacounts', 'tgaccounts')
    op.execute(
        """
        ALTER TABLE tgaccounts RENAME CONSTRAINT pk_tgacounts TO pk_tgaccounts;
        ALTER TABLE tgaccounts RENAME CONSTRAINT uq_tgacounts_api_id TO uq_tgaccounts_api_id;
        ALTER SEQUENCE tgacounts_id_seq RENAME TO tgaccounts_id_seq;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'job_start',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.drop_column('tasks', 'settings')
    op.add_column('roles', sa.Column('staff_action', postgresql.ARRAY(postgresql.ENUM('READ', 'WRITE', 'DELETE', 'UPDATE', name='actionchoice')), server_default=sa.text("'{}'::actionchoice[]"), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('role_action', postgresql.ARRAY(postgresql.ENUM('READ', 'WRITE', 'DELETE', 'UPDATE', name='actionchoice')), server_default=sa.text("'{}'::actionchoice[]"), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('bot_action', postgresql.ARRAY(postgresql.ENUM('READ', 'WRITE', 'DELETE', 'UPDATE', name='actionchoice')), server_default=sa.text("'{}'::actionchoice[]"), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('payment_action', postgresql.ARRAY(postgresql.ENUM('READ', 'WRITE', 'DELETE', 'UPDATE', name='actionchoice')), server_default=sa.text("'{}'::actionchoice[]"), autoincrement=False, nullable=False))
    op.rename_table('tgaccounts', 'tgacounts')
    op.execute(
        """
        ALTER TABLE tgacounts RENAME CONSTRAINT pk_tgaccounts TO pk_tgacounts;
        ALTER TABLE tgacounts RENAME CONSTRAINT uq_tgaccounts_api_id TO uq_tgacounts_api_id;
        ALTER SEQUENCE tgaccounts_id_seq RENAME TO tgacounts_id_seq;
        """
    )
    # ### end Alembic commands ###
