"""user server_defaults

Revision ID: 843bb6403190
Revises: 1561e5633238
Create Date: 2023-07-28 23:04:18.305158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843bb6403190'
down_revision = '1561e5633238'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'firstname',
               existing_type=sa.VARCHAR(),
               server_default='',
               nullable=False)
    op.alter_column('users', 'lastname',
               existing_type=sa.VARCHAR(),
               server_default='',
               nullable=False)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               server_default='',
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               server_default=None,
               nullable=True)
    op.alter_column('users', 'lastname',
               existing_type=sa.VARCHAR(),
               server_default=None,
               nullable=True)
    op.alter_column('users', 'firstname',
               existing_type=sa.VARCHAR(),
               server_default=None,
               nullable=True)
    # ### end Alembic commands ###
