"""change table name and name of columns

Revision ID: 9616c8dce03b
Revises: 70deb0fdbcda
Create Date: 2023-08-15 19:19:28.626844

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '9616c8dce03b'
down_revision = '70deb0fdbcda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_chats_members_chat_chats', 'chats_members', type_='foreignkey')
    op.drop_constraint('fk_chats_members_member_members', 'chats_members', type_='foreignkey')
    op.alter_column('chats', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('chats_members', 'chat', new_column_name='chat_id')
    op.alter_column('chats_members', 'member', new_column_name='member_id')
    op.rename_table('chats_members', 'chat_member')
    op.create_foreign_key(op.f('fk_chat_member_member_id_members'), 'chat_member', 'members', ['member_id'], ['id'])
    op.create_foreign_key(op.f('fk_chat_member_chat_id_chats'), 'chat_member', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_chat_member_member_id_members'), 'chat_member', type_='foreignkey')
    op.drop_constraint(op.f('fk_chat_member_chat_id_chats'), 'chat_member', type_='foreignkey')
    op.rename_table('chat_member', 'chats_members')
    op.alter_column('chats_members', 'chat_id', new_column_name='chat')
    op.alter_column('chats_members', 'member_id', new_column_name='member')
    op.alter_column('chats', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_foreign_key('fk_chats_members_chat_chats', 'chats_members', 'chats', ['chat'], ['id'])
    op.create_foreign_key('fk_chats_members_member_members', 'chats_members', 'members', ['member'], ['id'])

    # ### end Alembic commands ###
