"""subscribe_active

Revision ID: b796bf8cd20b
Revises: e3a72947e52c
Create Date: 2023-08-08 01:16:40.366497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b796bf8cd20b'
down_revision = 'e3a72947e52c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscribe', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('user_subscribe', sa.Column('auto_debit', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subscribe', 'auto_debit')
    op.drop_column('user_subscribe', 'active')
    # ### end Alembic commands ###
