"""user_balance

Revision ID: e3a72947e52c
Revises: 0525ced27760
Create Date: 2023-08-05 10:18:35.182079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a72947e52c'
down_revision = '0525ced27760'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('fk_payments_user_users', 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_payments_user_id_users'), 'payments', 'users', ['user_id'], ['id'])
    op.drop_column('payments', 'user')
    op.add_column('users', sa.Column('balance', sa.Numeric(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'balance')
    op.add_column('payments', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_payments_user_id_users'), 'payments', type_='foreignkey')
    op.create_foreign_key('fk_payments_user_users', 'payments', 'users', ['user'], ['id'])
    op.drop_column('payments', 'user_id')
    # ### end Alembic commands ###
