"""tariffs

Revision ID: 55f66eac9c02
Revises: 9a78d54bceef
Create Date: 2023-06-29 21:11:38.935107

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '55f66eac9c02'
down_revision = '9a78d54bceef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benefits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benefits')),
    sa.UniqueConstraint('name', name=op.f('uq_benefits_name'))
    )
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('limitation_days', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tariffs')),
    sa.UniqueConstraint('name', name=op.f('uq_tariffs_name'))
    )
    op.create_table('tariff_benefits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tariff_id', sa.Integer(), nullable=False),
    sa.Column('benefit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['benefit_id'], ['benefits.id'], name=op.f('fk_tariff_benefits_benefit_id_benefits')),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], name=op.f('fk_tariff_benefits_tariff_id_tariffs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tariff_benefits'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tariff_benefits')
    op.drop_table('tariffs')
    op.drop_table('benefits')
    # ### end Alembic commands ###
