"""role pretty name

Revision ID: d7e852625618
Revises: b796bf8cd20b
Create Date: 2023-08-14 00:51:06.763084

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'd7e852625618'
down_revision = 'b796bf8cd20b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('pretty_name', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'pretty_name')
    # ### end Alembic commands ###
