"""is_active -> is_banned

Revision ID: 70deb0fdbcda
Revises: d7e852625618
Create Date: 2023-08-14 20:55:11.904076

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '70deb0fdbcda'
down_revision = 'd7e852625618'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active', new_column_name='is_banned', server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_banned', new_column_name='is_active', server_default=sa.text('true'))
    # ### end Alembic commands ###
