"""Added user phone

Revision ID: 8f82e9ab0796
Revises: 213c83c48549
Create Date: 2023-07-20 14:56:33.594553

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '8f82e9ab0796'
down_revision = '213c83c48549'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.create_unique_constraint(op.f('uq_users_phone_number'), 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_phone_number'), 'users', type_='unique')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
