"""delete 'is_superuser' from models and add role into schema

Revision ID: 184df881dc21
Revises: e7321cdfbacd
Create Date: 2023-07-30 15:42:54.579595

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '184df881dc21'
down_revision = 'e7321cdfbacd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superuser')
    op.execute(
        "ALTER TYPE rolenamechoice ADD VALUE 'SUPERUSER';"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.execute(
        """
        ALTER TYPE rolenamechoice RENAME TO rolenamechoice_old;
        CREATE TYPE rolenamechoice AS ENUM('USER', 'ADMIN', 'ACCOUNTANT', 'HR');
        ALTER TABLE users ALTER COLUMN role_name DROP DEFAULT;
        ALTER TABLE users DROP CONSTRAINT fk_users_role_name_roles;
        ALTER TABLE users ALTER COLUMN role_name TYPE rolenamechoice USING role_name::text::rolenamechoice;
        ALTER TABLE roles ALTER COLUMN name TYPE rolenamechoice USING name::text::rolenamechoice;
        ALTER TABLE users ADD CONSTRAINT fk_users_role_name_roles FOREIGN KEY (role_name) REFERENCES roles(name);
        ALTER TABLE users ALTER COLUMN role_name SET DEFAULT 'USER';
        DROP TYPE rolenamechoice_old;
        """
    )
    # ### end Alembic commands ###
