"""user server_defaults

Revision ID: 225a3e639cb6
Revises: 1561e5633238
Create Date: 2023-07-28 23:14:34.575204

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '225a3e639cb6'
down_revision = '1561e5633238'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'firstname',
               existing_type=sa.VARCHAR(),
               server_default='',
               nullable=False)
    op.alter_column('users', 'lastname',
               existing_type=sa.VARCHAR(),
               server_default='',
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'lastname',
               existing_type=sa.VARCHAR(),
               server_default=None,
               nullable=True)
    op.alter_column('users', 'firstname',
               existing_type=sa.VARCHAR(),
               server_default=None,
               nullable=True)
    # ### end Alembic commands ###
