"""add tg accounts model

Revision ID: 9bbaf25b5c1c
Revises: 55f66eac9c02
Create Date: 2023-07-01 21:37:53.702880

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '9bbaf25b5c1c'
down_revision = '55f66eac9c02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tgacounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('api_hash', sa.String(length=400), nullable=False),
    sa.Column('session_string', sa.String(), nullable=False),
    sa.Column('work_status', sa.Enum('WORK', 'FREE', name='workchoice'), nullable=False),
    sa.Column('block_status', sa.Enum('BLOCK', 'UNBLOCK', name='blockchoice'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tgacounts')),
    sa.UniqueConstraint('api_id', name=op.f('uq_tgacounts_api_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tgacounts')
    op.execute(
        "DROP TYPE "
        "workchoice, "
        "blockchoice;"
    )
    # ### end Alembic commands ###
