repos:

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [ --line-length=80 ]

  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)
        exclude: db_init.py
        args: ["--profile", "black"]

      - id: isort
        name: isort (cython)
        types: [cython]
        args: ["--profile", "black"]

      - id: isort
        name: isort (pyi)
        types: [pyi]
        args: ["--profile", "black"]
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.17.4
    hooks:
      - id: pylint
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
    -   id: mypy

#isort pylint mypy