version: "3.9"

volumes:
  static_volume:

networks:
  backend_net:

services:
  backend:
    build: ./backend
    depends_on:
      postgresql:
        condition: service_healthy
    restart: always
    env_file:
      - .env
    ports:
      - 48656:8000
    networks:
      - backend_net

  postgresql:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 3s
    networks:
      - backend_net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - type: volume
        source: static_volume
        target: /var/www/staticfiles
        volume:
          nocopy: true
    depends_on:
      - backend
    networks:
      - backend_net


#  frontend:
#    build: ./tgparsing-front
#    ports:
#      - 80:80
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - backend
#      - postgresql

