version: "3.9"

services:
  postgresql:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 3s

  backend:
    build: ./
    depends_on:
      postgresql:
        condition: service_healthy
    restart: always
    env_file:
      - .env
    volumes:
      - ./app/:/app/
      - ./app/static:/app/static
    ports:
      - 80:8000
    entrypoint: ["sh", "run.sh"]


  redis:
    image: redis:6.0.20-alpine
    container_name: redis

  celery_worker:
    build: ./
    container_name: celery_worker
    depends_on:
      - redis
    volumes:
        - ./app:/app/
    command: celery -A utils.celery.celery_app worker -l DEBUG
    env_file:
      - .env
    
  celery_beat:
    build: ./
    container_name: celery_beat
    depends_on:
      - celery_worker
    command: celery -A utils.celery.celery_app beat -l DEBUG
    volumes:
        - ./app/:/app/
    env_file:
      - .env