# black
[tool.black]
line-length = 79
extend-exclude = "migrations/"

# isort
[tool.isort]
profile = "black"

# pytest
[tool.pytest.ini_options]
addopts = "-v"
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
testpaths = ["tests"]
asyncio_mode = "auto"
filterwarnings = [
    "ignore:pkg_resources is deprecated as an API:DeprecationWarning"
]

# mypy
[tool.mypy]
exclude = ["migrations/"]

[tool.pylint.BASIC]
# Good variable names which should always be accepted, separated by a comma.
good-names = '''
    id,
'''

[tool.pylint.MASTER]
ignore = [".git", "__pycache__", "migrations", ".venv"]
extension-pkg-whitelist = "pydantic"

[tool.pylint.format]
max-line-length = 79

[tool.pylint.DESIGN]
# Maximum number of arguments for function / method.
max-args = 7

[tool.pylint."MESSAGES CONTROL"]
disable = '''
    C0114,
    C0115,
    C0116,
    W,
    too-few-public-methods
'''
