# black
[tool.black]
line-length = 79
extend-exclude = "migrations/"

[tool.isort]
profile = "black"

# pytest
[tool.pytest.ini_options]
addopts = "-v"
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
testpaths = ["tests"]
asyncio_mode = "auto"
filterwarnings = [
    "ignore:pkg_resources is deprecated as an API:DeprecationWarning"
]

# pytest-pytest_alembic
pytest_alembic_tests_path = "tests/pytest_alembic"
#pytest_alembic_exclude = "test_alembic.py"
#pytest_alembic_tests_path = "tests/pytest_alembic"

[tool.mypy]
exclude = ["migrations/"]

[tool.pylint.MASTER]
ignore = [".git", "__pycache__", "migrations", ".venv"]
extension-pkg-whitelist = "pydantic"

[tool.pylint.format]
max-line-length = 79

[tool.pylint.DESIGN]

# Maximum number of arguments for function / method.
max-args = 7

[tool.pylint."MESSAGES CONTROL"]
disable = '''
    C0114,
    C0115,
    C0116,
    C0103,
    W,
    too-few-public-methods
'''
