# black
[tool.black]
line-length = 79

# pytest
[tool.pytest.ini_options]
addopts = "-rsxX -v"
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
testpaths = ["tests"]
asyncio_mode = "auto"
filterwarnings = [
    "ignore:pkg_resources is deprecated as an API:DeprecationWarning"
]