# black
[tool.black]
line-length = 79

# pytest
[tool.pytest.ini_options]
addopts = "-v"
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
testpaths = ["tests"]
asyncio_mode = "auto"
filterwarnings = [
    "ignore:pkg_resources is deprecated as an API:DeprecationWarning"
]

# pytest-pytest_alembic
pytest_alembic_tests_path = "tests/pytest_alembic"
#pytest_alembic_exclude = "test_alembic.py"
#pytest_alembic_tests_path = "tests/pytest_alembic"