"""tgmembers

Revision ID: 76e92afa5b88
Revises: b3d9f56436a7
Create Date: 2023-07-01 11:37:00.883846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76e92afa5b88'
down_revision = 'b3d9f56436a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_members',
    sa.Column('tguser_id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('tguser_id', name=op.f('pk_chat_members'))
    )
    op.create_index(op.f('ix_chat_members_username'), 'chat_members', ['username'], unique=True)
    op.create_table('parsered_chats',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('chat_id', name=op.f('pk_parsered_chats'))
    )
    op.create_index(op.f('ix_parsered_chats_name'), 'parsered_chats', ['name'], unique=True)
    op.create_table('chats_in_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_member_name', sa.String(), nullable=False),
    sa.Column('parsered_chat_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['chat_member_name'], ['chat_members.username'], name=op.f('fk_chats_in_members_chat_member_name_chat_members')),
    sa.ForeignKeyConstraint(['parsered_chat_name'], ['parsered_chats.name'], name=op.f('fk_chats_in_members_parsered_chat_name_parsered_chats')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chats_in_members'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_tariffs_name'), 'tariffs', type_='unique')
    op.create_unique_constraint('name_unique', 'tariffs', ['name'])
    op.alter_column('payments', 'amount',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('payments', 'status')
    op.drop_table('chats_in_members')
    op.drop_index(op.f('ix_parsered_chats_name'), table_name='parsered_chats')
    op.drop_table('parsered_chats')
    op.drop_index(op.f('ix_chat_members_username'), table_name='chat_members')
    op.drop_table('chat_members')
    # ### end Alembic commands ###
