"""change name table

Revision ID: 59548c516692
Revises: 3d5571355882
Create Date: 2023-06-04 00:00:03.806700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "59548c516692"
down_revision = "3d5571355882"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("payment", "payments")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("payments", "payment")
    # ### end Alembic commands ###
