"""change tariff

Revision ID: ba55bc301cd4
Revises: 245907d587fd
Create Date: 2023-07-24 09:49:03.969990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba55bc301cd4'
down_revision = '245907d587fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariffs', sa.Column('period', sa.String(length=10), nullable=False))
    op.drop_column('tariffs', 'limitation_days')
    op.add_column('user_subscribe', sa.Column('options', sa.JSON(), nullable=False))
    op.add_column('user_subscribe', sa.Column('end_date', sa.DateTime(), nullable=False))
    op.add_column('user_subscribe', sa.Column('autopay', sa.Boolean(), nullable=False))
    op.drop_column('user_subscribe', 'start_date')
    op.drop_column('user_subscribe', 'tariff_options')
    op.add_column('users', sa.Column('balance', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'balance')
    op.add_column('user_subscribe', sa.Column('tariff_options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('user_subscribe', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('user_subscribe', 'autopay')
    op.drop_column('user_subscribe', 'end_date')
    op.drop_column('user_subscribe', 'options')
    op.add_column('tariffs', sa.Column('limitation_days', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('tariffs', 'period')
    # ### end Alembic commands ###
