"""Add accounts

Revision ID: 08d8a6218cf3
Revises: d61a73e95878
Create Date: 2023-06-02 17:19:33.796720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "08d8a6218cf3"
down_revision = "d61a73e95878"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telegram_accounts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("api_id", sa.Integer(), nullable=False),
        sa.Column("api_hash", sa.String(), nullable=False),
        sa.Column("session", sa.String(), nullable=False),
        sa.Column("is_blocked", sa.Boolean(), nullable=True),
        sa.Column("is_worked", sa.Boolean(), nullable=True),
        sa.Column("by_geo", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("telegram_accounts")
    # ### end Alembic commands ###
