"""payment

Revision ID: d61a73e95878
Revises: 7059deaf392f
Create Date: 2023-06-02 16:11:22.466273

"""
from alembic import op
import sqlalchemy as sa

from database.models.user_model import payment_type

# revision identifiers, used by Alembic.
revision = "d61a73e95878"
down_revision = "7059deaf392f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user", sa.Integer(), nullable=False),
        sa.Column(
            "user_action",
            sa.Enum("debit", "credit", name="user_payment"),
            nullable=False,
        ),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("date", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user"], ["users.id"], name="payment_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tariffs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tariffs")
    op.drop_table("payment")
    payment_type.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
