"""add columns into roles

Revision ID: be259c269e5c
Revises: b63dc9b97663
Create Date: 2023-06-13 16:24:21.090141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "be259c269e5c"
down_revision = "b63dc9b97663"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE rolenamechoice ADD VALUE 'HR';")
    op.add_column(
        "roles",
        sa.Column(
            "role_action",
            postgresql.ARRAY(
                sa.Enum(
                    "READ", "WRITE", "DELETE", "UPDATE", name="actionchoice"
                )
            ),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column(
        "roles",
        sa.Column(
            "bot_action",
            postgresql.ARRAY(
                sa.Enum(
                    "READ", "WRITE", "DELETE", "UPDATE", name="actionchoice"
                )
            ),
            server_default="{}",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("roles", "bot_action")
    op.drop_column("roles", "role_action")
    op.execute(
        """
        DELETE FROM roles WHERE name = 'HR';
        ALTER TYPE rolenamechoice RENAME TO rolenamechoice_old;
        CREATE TYPE rolenamechoice AS ENUM('USER', 'ADMIN', 'ACCOUNTANT');
        ALTER TABLE users DROP CONSTRAINT users_role_name_fkey;
        ALTER TABLE users ALTER COLUMN role_name DROP DEFAULT;
        ALTER TABLE roles ALTER COLUMN name TYPE rolenamechoice
            USING name::text::rolenamechoice;
        ALTER TABLE users ALTER COLUMN role_name TYPE rolenamechoice 
            USING role_name::text::rolenamechoice;
        ALTER TABLE users ADD CONSTRAINT users_role_name_fkey 
            FOREIGN KEY (role_name) REFERENCES roles(name);
        ALTER TABLE users ALTER COLUMN role_name 
            SET DEFAULT 'USER'::rolenamechoice;
        DROP TYPE rolenamechoice_old;
        """
    )
    # ### end Alembic commands ###
