"""tgmembers

Revision ID: 2c766d7b4ae9
Revises: 280610ccc91c
Create Date: 2023-06-25 09:06:38.046858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c766d7b4ae9'
down_revision = '280610ccc91c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsered_chats',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id'),
    sa.UniqueConstraint('name', name='chatname_unique')
    )
    op.create_table('chat_members',
    sa.Column('tguser_id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('chat_names', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['chat_names'], ['parsered_chats.name'], ),
    sa.PrimaryKeyConstraint('tguser_id'),
    sa.UniqueConstraint('username', name='tgusername_unique')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_members')
    op.drop_table('parsered_chats')
    # ### end Alembic commands ###
