"""upd payments

Revision ID: c7f20cd4b794
Revises: b63dc9b97663
Create Date: 2023-06-14 13:49:31.860970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c7f20cd4b794"
down_revision = "b63dc9b97663"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments", sa.Column("status", sa.Boolean(), nullable=False)
    )
    op.alter_column(
        "payments",
        "amount",
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "payments",
        "amount",
        existing_type=sa.Numeric(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_column("payments", "status")
    # ### end Alembic commands ###
