"""add_model_tgaccont

Revision ID: d555ae763812
Revises: 7bbf58250ecb
Create Date: 2023-06-10 11:49:24.281665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd555ae763812'
down_revision = '7bbf58250ecb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tgacounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('api_hash', sa.String(), nullable=False),
    sa.Column('session_strins', sa.String(), nullable=False),
    sa.Column('in_work', sa.Boolean(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('by_geo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'api_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tgacounts')
    # ### end Alembic commands ###
