"""add chat and member models

Revision ID: 75b809694e2d
Revises: 8883acfbfc32
Create Date: 2023-07-06 11:33:56.977869

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '75b809694e2d'
down_revision = '8883acfbfc32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chats'))
    )
    op.create_index(op.f('ix_chats_title'), 'chats', ['title'], unique=True)
    op.create_index(op.f('ix_chats_username'), 'chats', ['username'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_members'))
    )
    op.create_index(op.f('ix_members_username'), 'members', ['username'], unique=True)
    op.create_table('chats_members',
    sa.Column('chat', sa.Integer(), nullable=False),
    sa.Column('member', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['chat'], ['chats.id'], name=op.f('fk_chats_members_chat_chats')),
    sa.ForeignKeyConstraint(['member'], ['members.id'], name=op.f('fk_chats_members_member_members')),
    sa.PrimaryKeyConstraint('chat', 'member', name=op.f('pk_chats_members'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chats_members')
    op.drop_index(op.f('ix_members_username'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_chats_username'), table_name='chats')
    op.drop_index(op.f('ix_chats_title'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
