"""add is_active for table "roles"

Revision ID: 7bbf58250ecb
Revises: 59548c516692
Create Date: 2023-06-05 11:01:48.022561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7bbf58250ecb"
down_revision = "59548c516692"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("roles", sa.Column("is_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("roles", "is_active")
    # ### end Alembic commands ###
