"""add_tgaccount

Revision ID: 2efcc237721d
Revises: 7bbf58250ecb
Create Date: 2023-06-13 15:53:22.678250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2efcc237721d'
down_revision = '7bbf58250ecb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tgacounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('api_hash', sa.String(), nullable=False),
    sa.Column('session_string', sa.String(), nullable=False),
    sa.Column('work', sa.Enum('WORK', 'FREE', 'EMPTY', name='workchoice'), nullable=False),
    sa.Column('blocked', sa.Enum('BLOCK', 'UN_BLOCK', 'EMPTY', name='blockchoice'), nullable=False),
    sa.Column('by_geo', sa.Enum('BY_GEO', 'NOT_GEO', 'EMPTY', name='geochoice'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tgacounts')
    op.execute("DROP TYPE workchoice, blockchoice, geochoice")
    # ### end Alembic commands ###
