"""tariff

Revision ID: 7ef992ded889
Revises: be259c269e5c
Create Date: 2023-06-19 17:35:47.211002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef992ded889'
down_revision = 'be259c269e5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariff_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tariff', sa.Integer(), nullable=False),
    sa.Column('limitation', sa.Enum('DAY', 'WEEK', 'MONTH', name='tarifflimitchoices'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tariff'], ['tariffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tariffs', sa.Column('description', sa.JSON(), nullable=False))
    op.create_unique_constraint(None, 'tariffs', ['name'])
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(),
               server_default='/mnt/c/Users/Alone/PycharmProjects/tgparsing/backend/static/users_avatars/base_avatar.png',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'/home/igor/Software_projects/Portfolio/tgparsing/backend/static/users_avatars/base_avatar.png'::character varying"),
               existing_nullable=False)
    op.drop_constraint(None, 'tariffs', type_='unique')
    op.drop_column('tariffs', 'description')
    op.drop_table('tariff_price')
    # ### end Alembic commands ###
