"""add tasks

Revision ID: 089845b2b7c2
Revises: 213c83c48549
Create Date: 2023-07-20 22:32:34.268005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089845b2b7c2'
down_revision = '213c83c48549'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('job_start', sa.DateTime(), nullable=True),
    sa.Column('job_finish', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('operation', sa.Enum('PARSING', 'MAILING', name='operationchoice'), server_default='PARSING', nullable=False),
    sa.Column('work_status', sa.Enum('IN_PROCESSING', 'IN_WAITING', 'FAILED', 'SUCCESS', name='workstatuschoice'), server_default='IN_PROCESSING', nullable=False),
    sa.Column('data_count', sa.Integer(), nullable=False),
    sa.Column('time_work', sa.TIME(), nullable=False),
    sa.Column('favorite', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tasks_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.drop_table('tasks')
    op.execute(
        "DROP TYPE operationchoice, workstatuschoice;"
    )
    # ### end Alembic commands ###
