"""user.balance

Revision ID: 0ab6851eb9b0
Revises: 213c83c48549
Create Date: 2023-07-19 09:04:46.371941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ab6851eb9b0'
down_revision = '213c83c48549'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscribe', sa.Column('end_date', sa.DateTime(), nullable=False))
    op.drop_column('user_subscribe', 'start_date')
    op.add_column('users', sa.Column('balance', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'balance')
    op.add_column('user_subscribe', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('user_subscribe', 'end_date')
    # ### end Alembic commands ###
