"""change usersubscribe.end_date

Revision ID: e958ff6b7228
Revises: 196f435444ec
Create Date: 2023-07-11 15:46:57.405767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e958ff6b7228'
down_revision = '196f435444ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscribe', sa.Column('end_date', sa.DateTime(), nullable=False))
    op.drop_column('user_subscribe', 'start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscribe', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('user_subscribe', 'end_date')
    # ### end Alembic commands ###
