"""fix_model

Revision ID: b00fb248b2d8
Revises: d555ae763812
Create Date: 2023-06-11 13:34:58.503423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b00fb248b2d8'
down_revision = 'd555ae763812'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
