"""null columns in tgmember

Revision ID: 63a266d3a70e
Revises: b3d9f56436a7
Create Date: 2023-06-27 22:39:03.512946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63a266d3a70e'
down_revision = 'b3d9f56436a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_members', 'firstname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chat_members', 'lastname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('parsered_chats', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parsered_chats', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chat_members', 'lastname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chat_members', 'firstname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
