"""tgaccont_model

Revision ID: 38f691e3b5fb
Revises: be259c269e5c
Create Date: 2023-06-20 20:58:20.515576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38f691e3b5fb'
down_revision = 'be259c269e5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tgacounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('api_hash', sa.String(), nullable=False),
    sa.Column('session_string', sa.String(), nullable=False),
    sa.Column('work', sa.Enum('WORK', 'FREE', 'EMPTY', name='workchoice'), nullable=False),
    sa.Column('blocked', sa.Enum('BLOCK', 'UN_BLOCK', 'EMPTY', name='blockchoice'), nullable=False),
    sa.Column('by_geo', sa.Enum('BY_GEO', 'NOT_GEO', 'EMPTY', name='geochoice'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(),
               server_default='static/users_avatars/base_avatar.png',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'/home/igor/Software_projects/Portfolio/tgparsing/backend/static/users_avatars/base_avatar.png'::character varying"),
               existing_nullable=False)
    op.drop_table('tgacounts')
    op.execute("DROP TYPE workchoice, blockchoice, geochoice")
    # ### end Alembic commands ###
