"""balance

Revision ID: 041f03e33f32
Revises: 7059deaf392f
Create Date: 2023-06-02 10:12:22.963768

"""
from alembic import op
import sqlalchemy as sa

from database.models.user_model import payment_type

# revision identifiers, used by Alembic.
revision = '041f03e33f32'
down_revision = '7059deaf392f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_charge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('user_action', sa.Enum('debit', 'credit', name='user_payment'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='usercharge_user_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key('user_role_name_fkey', 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_role_name_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.drop_table('tariffs')
    op.drop_table('user_charge')
    op.drop_table('roles')
    payment_type.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
