"""add phone number into tgaccounts

Revision ID: 8883acfbfc32
Revises: 9bbaf25b5c1c
Create Date: 2023-07-06 11:11:26.889374

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '8883acfbfc32'
down_revision = '9bbaf25b5c1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tgacounts', sa.Column('phone_number', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tgacounts', 'phone_number')
    # ### end Alembic commands ###
