"""add member model and change tgaccounts

Revision ID: d5409b7a1231
Revises: 9bbaf25b5c1c
Create Date: 2023-07-03 21:34:11.337760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5409b7a1231'
down_revision = '9bbaf25b5c1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chats'))
    )
    op.create_index(op.f('ix_chats_title'), 'chats', ['title'], unique=True)
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_members'))
    )
    op.create_index(op.f('ix_members_username'), 'members', ['username'], unique=True)
    op.create_table('chats_members',
    sa.Column('chat', sa.Integer(), nullable=False),
    sa.Column('member', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat'], ['chats.id'], name=op.f('fk_chats_members_chat_chats')),
    sa.ForeignKeyConstraint(['member'], ['members.id'], name=op.f('fk_chats_members_member_members')),
    sa.PrimaryKeyConstraint('chat', 'member', name=op.f('pk_chats_members'))
    )
    op.add_column('tgacounts', sa.Column('phone_number', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tgacounts', 'phone_number')
    op.drop_table('chats_members')
    op.drop_index(op.f('ix_members_username'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_chats_title'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
