"""Initial

Revision ID: 280610ccc91c
Revises: 
Create Date: 2023-06-24 21:25:37.208166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '280610ccc91c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.Enum('USER', 'ADMIN', 'ACCOUNTANT', 'HR', name='rolenamechoice'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('staff_action', postgresql.ARRAY(sa.Enum('READ', 'WRITE', 'DELETE', 'UPDATE', name='actionchoice')), server_default='{}', nullable=False),
    sa.Column('payment_action', postgresql.ARRAY(sa.Enum('READ', 'WRITE', 'DELETE', 'UPDATE', name='actionchoice')), server_default='{}', nullable=False),
    sa.Column('role_action', postgresql.ARRAY(sa.Enum('READ', 'WRITE', 'DELETE', 'UPDATE', name='actionchoice')), server_default='{}', nullable=False),
    sa.Column('bot_action', postgresql.ARRAY(sa.Enum('READ', 'WRITE', 'DELETE', 'UPDATE', name='actionchoice')), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_roles'))
    )
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tariffs')),
    sa.UniqueConstraint('name', name=op.f('uq_tariffs_name'))
    )
    op.create_table('tariff_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tariff', sa.Integer(), nullable=False),
    sa.Column('limitation', sa.Enum('DAY', 'WEEK', 'MONTH', name='tarifflimitchoices'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tariff'], ['tariffs.id'], name=op.f('fk_tariff_price_tariff_tariffs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tariff_price'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('avatar_url', sa.String(), server_default='static/users_avatars/base_avatar.png', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('True'), nullable=False),
    sa.Column('is_staff', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('role_name', sa.Enum('USER', 'ADMIN', 'ACCOUNTANT', 'HR', name='rolenamechoice'), server_default='USER', nullable=False),
    sa.ForeignKeyConstraint(['role_name'], ['roles.name'], name=op.f('fk_users_role_name_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('DEBIT', 'CREDIT', name='paymentchoice'), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name=op.f('fk_payments_user_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tariff_price')
    op.drop_table('tariffs')
    op.drop_table('roles')
    op.execute(
        "DROP TYPE "
            "rolenamechoice, "
            "actionchoice, "
            "tarifflimitchoices, "
            "paymentchoice;"
    )
    # ### end Alembic commands ###
